configuration: Release

skip_commits:
  files:
  - '*.md'

nuget:
  account_feed: true
  
init:
  - git config --global core.autocrlf true
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

build:
  verbosity: normal

before_build:
 - ps: dotnet restore

test: off

test_script:
 - ps: >-

    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
    
    choco install opencover.portable -y

    ForEach ($folder in (Get-ChildItem -Path .\ -Directory -Filter *.Tests)) { 

    dotnet test $folder.FullName -xml ($folder.FullName + "\xunit-results.xml") 

    $openCover = 'C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe'
    
    $targetArgs = '-targetargs: test ' + $folder.FullName + ' -c ' + $ENV:CONFIGURATION + '-register:user -oldStyle -mergeoutput -output:' + $ENV:APPVEYOR_BUILD_FOLDER + 'coverage.xml'

    $filter = '-filter:-[*.Tests]*'

    & $openCover '-target:C:\Program Files\dotnet\dotnet.exe' $targetArgs $filter 
    
    }

after_test:
  - bash <(curl -s https://codecov.io/bash)