configuration: Release

skip_commits:
  files:
  - '*.md'

init:
  - git config --global core.autocrlf true
  
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - ps: >-
  
    Write-Host "Downloading latest .NET Core SDK..."

    (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=843448', 'dotnet-core-sdk.exe')
 
    Write-Host "Installing .NET Core SDK..."
 
    Start-Process "dotnet-core-sdk.exe" "/install /quiet /norestart" -Wait

 - nuget sources add -Name wopi -Source %nuget_feed%
 - "python.exe -m pip install codecov"

build:
  verbosity: normal

before_build:
 - ps: dotnet restore

test: off

test_script:
 - ps: >-

    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
    
    choco install opencover.portable -y

    ForEach ($folder in (Get-ChildItem -Path .\ -Directory -Filter *.Tests)) { 
    
    Write-Host $folder.FullName

    dotnet test $folder.FullName -xml ($folder.FullName + "\xunit-results.xml") 

    $openCover = 'C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console.exe'
    
    $targetArgs = '-targetargs: test ' + $folder.FullName + ' -c ' + $ENV:CONFIGURATION

    $filter = '-filter:+[Wopi*]*-[*Tests]*'

    & $openCover '-target:C:\Program Files\dotnet\dotnet.exe' $targetArgs '-register:user' $filter '-oldStyle' '-mergeoutput' ('-output:' + $ENV:APPVEYOR_BUILD_FOLDER + '\coverage.xml')
    
    }

after_test:
  - "codecov"
