skip_commits:
  files:
  - *.md

nuget:
  account_feed: true
  
init:
  - git config --global core.autocrlf true
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

build:
  verbosity: normal

before_build:
 - ps: dotnet restore

test: off

#test_script:
# - ps: >-
#    cd .\WopiHost.FileSystemProvider.Tests
#
#   dnx test -xml xunit-results.xml
#
#    $wc = New-Object 'System.Net.WebClient'
#
#$wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))