version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout       
      - run:
          name: Restore packages
          command: | 
            dotnet restore
      - run:
          name: Restore from private NuGet feed
          command: | 
            dotnet restore -s ${myget_feed}
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: | 
            dotnet test
